export const dataSet = {
  set1: [
    {
      title: 'Revenue',
      subtitle: 'US$, in thousands',
      ranges: [100, 350, 500],
      measures: [390],
      markers: [410],
    },
    {
      title: 'Profit',
      subtitle: '%',
      ranges: [20, 25, 30],
      measures: [21],
      markers: [26],
    },
    {
      title: 'Order Size',
      subtitle: 'US$, average',
      ranges: [350, 500, 600],
      measures: [100],
      markers: [550],
    },
    {
      title: 'New Customers',
      subtitle: 'count',
      ranges: [1400, 2000, 2500],
      measures: [1000],
      markers: [2100],
    },
    {
      title: 'Satisfaction',
      subtitle: 'out of 5',
      ranges: [3.5, 4.25, 5],
      measures: [3.2],
      markers: [4.4],
    },
  ],
  set2: [
    {
      title: 'Revenue',
      subtitle: 'US$, in thousands',
      ranges: [150, 225, 300],
      measures: [220],
      markers: [250],
    },
    {
      title: 'Profit',
      subtitle: '%',
      ranges: [20, 25, 30],
      measures: [21],
      markers: [26],
    },
    {
      title: 'Order Size',
      subtitle: 'US$, average',
      ranges: [350, 500, 600],
      measures: [100],
      markers: [550],
    },
    {
      title: 'New Customers',
      subtitle: 'count',
      ranges: [1400, 2000, 2500],
      measures: [1000],
      markers: [2100],
    },
    {
      title: 'Satisfaction',
      subtitle: 'out of 5',
      ranges: [3.5, 4.25, 5],
      measures: [3.2],
      markers: [4.4],
    },
  ],
};
